### ISSUE TITLE
[BUG] Can't install with does not contain a valid manifest error

### ISSUE THREAD

**Issue by amano-takahisa** [tefkah/zotero-night#104]
**Describe the bug**
I tried install v0.4.20 to Firefox 110.0.1 on Arch Linux,
but couldn't install with "... because appear to be corrupt" message.
![image](https://user-images.githubusercontent.com/51368373/224577437-320298e7-62c2-4442-9b74-2474fe4deefb.png)

**To Reproduce**
1. Go to release page with Firefox,
2. Click on `.xpi` file, and try install.

Same even I download `xpi` file to local, and tried to install from the file.

With debug mode, error message says "not contains a valid manifest."
![image](https://user-images.githubusercontent.com/51368373/224577753-a73f9c4d-a637-4f36-91bd-305e53424875.png)

**Comment by amano-takahisa** [comment]
Sorry, I completely misunderstood about plugin😅


I could install to Zotero.

**Comment by tefkah** [comment]
Glad you resolved it!
