### ISSUE TITLE
[BUG] Default PDF filter does nothing

### ISSUE THREAD

**Issue by tonydavis629** [tefkah/zotero-night#105]
**Describe the bug**
PDFs always load without filtering, full white. I can click the filter on top of the pdf to change it, which works normally, but the default is always none. The rest of dark mode works normally.

**To Reproduce**
- Install zotero-night 
- set default pdf filter 
- get blinded by a PDF

**Expected behavior**
PDFs should load with respect to the default filter settings

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
Windows 10

**Zotero Night version (please check that you are on the latest version)**
0.4.20

**Comment by bbalanza** [comment]
Please see #84 for a solution, although not optimal :)
