### ISSUE TITLE
[BUG] When more than three pdf tabs are open, clicking on fourth tab causes refresh and pdf goes back to default white mode 

### ISSUE THREAD

**Issue by pbk0** [tefkah/zotero-night#106]
**Describe the bug**
Firstly, opening a new PDF tab does not use dark mode. Then when I open three PDF tabs all open in white mode and I switch each PDF to black theme. But then when I open the fourth PDF tab and go back to the first PDF tab, it refreshes and switches back to normal mode. Everything is fine until three tabs are open, after that, the add-on keeps forgetting the PDF theme color we set.

**To Reproduce**
Try to open more than three PDFs and set them to dark mode.
Then try to click on the first PDF tab. You will see that causes refresh and forgets the theme selected.

**Expected behavior**
The selected mode should persist and after refresh it should be using the old theme that we set

**Screenshots**
See the GIF below. 
I go to each of the four PDF tabs and change the theme to dark.
Then when I go on third and second thing are fine, and the tabs are in dark mode.
But when I go to the first PDF tab then add-on refreshed the tab and goes back to the normal theme
![bug](https://user-images.githubusercontent.com/2289914/226160600-919f793e-5846-42f0-8db0-a4b73e993d70.gif)

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
Windows

**Zotero Night version (please check that you are on the latest version)**
v0.4.20 (latest)

**Comment by medecine-max** [comment]
+1
​I tested it on my surface and desk-pc, one for night and the other for light.
![image](https://user-images.githubusercontent.com/73583017/231678892-16fb6afb-1eb6-4d28-a7ce-686a7a00fb19.png)
![image](https://user-images.githubusercontent.com/73583017/231679489-a1240a0f-c9c3-4c7a-9b66-a695bb17f934.png)

**Comment by FriendG1973** [comment]
Thank you for everything, but the bug is also on mac
@tefkah

**Comment by tefkah** [comment]
this should be fixed. i think this has something to do with maybe some new memory cleaning mechanism by zotero.

I fixed this by actually having zotero night remember your setting per tab, so even if it reloads it will go back to the same setting.
