### ISSUE TITLE
[BUG] back to light mode not work well

### ISSUE THREAD

**Issue by EthanSystem** [tefkah/zotero-night#111]
**Describe the bug**

When I switch from dark mode to light mode, the existing interface cannot be switched back. Stand-alone windows are not affected. In addition, the independent window is not affected by whether or not to switch modes.

The hardware and software configuration is:

Apple M1 Pro 2021 , Mac OS 13.3.1 , Zotero 6.0.23, Night for Zotero 0.4.20, Zotero Better Notes 0.8.9 .

**Additional context**
It looks like this:

![image](https://user-images.githubusercontent.com/26479459/232179648-8fdc7036-7dfc-4305-9510-ab055b1ad960.png)

**Comment by tefkah** [comment]
Is this still an issue in the latest version? If so, please reopen!
