### ISSUE TITLE
[BUG] Not work in Zotero 6.0.23 Windows 10

### ISSUE THREAD

**Issue by matchyc** [tefkah/zotero-night#112]
**Describe the bug**
Just follow the video instruction, but didn't work.

Windows 21H2

**Comment by sutzig** [comment]
Doesn't seem to be working on Mac OS with Zotero 6.0.26 either

**Comment by TheDarkTron** [comment]
Same here.
I installed [zotero-night-0.4.20.xpi](https://github.com/tefkah/zotero-night/releases/download/v0.4.20/zotero-night-0.4.20.xpi) and restarted zotero. Afterwards zotero still looks the same. PDFs also look the same. 
I then uninstalled the extension and installed [night.xpi](https://github.com/tefkah/zotero-night/releases/download/v0.4.20/night.xpi) with the same outcome.
Using:
Win 11 Edu 
Version 22H2 
OS build 22621.1702
Zotero 6.0.26

**Comment by LennyHirsch** [comment]
Try going to Tools > Night Preferences and then click "Enable Dark Theme" in the pop-up window.
Zotero Night is not enabled by default on Windows, not sure about MacOS or Linux.

Pull request #117 seeks to update the instructions to address this issue.

**Comment by matchyc** [comment]
> Try going to Tools > Night Preferences and then click "Enable Dark Theme" in the pop-up window. Zotero Night is not enabled by default on Windows, not sure about MacOS or Linux.
> 
> Pull request #117 seeks to update the instructions to address this issue.

it works! thanks a lot
