### ISSUE TITLE
[BUG] Looks awful on Windows

### ISSUE THREAD

**Issue by huachuman** [tefkah/zotero-night#115]
I am not sure there is much to say. Was this designed to work with Windows? Because it's pretty bad...

**Comment by tefkah** [comment]
are you referring to anything in particular? i know that the scrollbars are a particularly bad look on windows, but not much i can do about that until Zotero 7.

if not i will close this, not very constructive

**Comment by huachuman** [comment]
It's more of a question than anything. I'm just wondering if it's something wrong with my zotero but it doesn't look like the picture, at all. I recommend adding a screenshot of what it looks like on windows so we don't waste our time.

**Comment by Jarartur** [comment]
But it's actually good? What do you mean by awful? On mine installation it actually looks like on the screenshots.

**Comment by tefkah** [comment]
Hmm that is strange, could you add a screenshot of what it look like for you @huachuman? 
I have tested it on windows before and it should look roughly the same as on Mac, if not there is something going wrong. What version of Windows and Zotero are you using?

**Comment by huachuman** [comment]
I wanted to see if this would do anything better than just manually styling it dark mode. I had previously done dark mode myself by modifying all the code to my liking and was hoping that this plugin would have done a better job, like the scroll bars for example. 

The scroll bars entirely ruin the experience in windows. It's super finnicky especially with menu items and preferences, it just does not look good/native. It looks hacky.

I entirely respect that this is a limitation of zotero, not your work. But I think it's only fair to put a screenshot up of what it looks like in Windows (with the ugly as sin scrollbars and all the less appetizing aspects where it fails) if we're going to be fair.

If you don't get around to it yourself I'll share some example screenshots when I get back to town over the weekend.

**Comment by nhan000** [comment]
@huachuman any updates?
