### ISSUE TITLE
[FEAT] Zotero 7 beta support

### ISSUE THREAD

**Issue by jangid19** [tefkah/zotero-night#121]
**Describe the bug**
New beta version of Zotero is out (Zotero 7 beta). It provides native support for apple silicon and a variety of other enhancements to the codebase. Unfortunately, this means a lot of the extensions need to be updated to support Zotero 7.

**To Reproduce**
1. Go to [beta builds](https://www.zotero.org/support/beta_builds) page on zotero.
2. Download Zotero 7 beta
3. Try installing night-3.xpi
4. See error:- The add-on "night-3.xpi" could not be installed. It may be incompatible with this version of Zotero.

**Expected behavior**
Should be able to install Zotero Night on Zotero 7 beta.

**Screenshots**
<img width="1015" alt="Night_for_zotero" src="https://github.com/tefkah/zotero-night/assets/91697574/4321084c-7697-4f3c-b7c5-580e135f942f">

**OS type**
OS (MacOS Ventura 13.5 [Apple M1 Pro]

**Zotero Night version (please check that you are on the latest version)**
Zotero Night version v0.4.20

**Comment by freshman-x** [comment]
the same problem

**Comment by tefkah** [comment]
Ah that's great! I have been meaning to upgrade it to Zotero 7 but have not found the time for it yet, but I do mean to support it.

**Comment by Thesoul20** [comment]
the same problem, on Ubuntu 22.04

**Comment by tefkah** [comment]
making good progress!

Zotero 7 requires me to basically rewrite the entire plugin, bc it won't support the old style of plugin that I was using anymore. I was dreading this a bit, but thanks to Zotero Wizard [windingwind](https://github.com/windingwind) and their [fantastic plugin template](https://github.com/windingwind/zotero-plugin-template) it's getting there!

 

<img width="1074" alt="image" src="https://github.com/tefkah/zotero-night/assets/21983833/e518af88-0fb4-46e3-9c73-9e209a93c717">

**Comment by Thesoul20** [comment]
That is to say we can use Zotero-night on Zotero 7 in a short time?

**Comment by tefkah** [comment]
Yes.

**Comment by happyTonakai** [comment]
Would you make it as a pre-release? Still incompatible with zotero 7 with the latest night v0.4.23.

**Comment by tefkah** [comment]
I will put up a useable version as soon as possible.
It will be clearly distinguished from the other version

**Comment by jangid19** [comment]
Hi @tefkah, thanks a lot for all your effort on the porting of Zotero Night on Z7. Did you already put up a usable version that I can test on Z7? I was not able to install the latest release on Z7 beta.

**Comment by Meonthb** [comment]
Hi, @tefkah, thank you for your work! Could you release a preview version usable on Zotero 7?

**Comment by Jude24to25** [comment]
> I will put up a useable version as soon as possible. It will be clearly distinguished from the other version

This would be soooo great! Last night I was trying to use Zotero (light version), but my eyes were blinded, LOL. Can't wait to have access to a dark version!

**Comment by tefkah** [comment]
Hi All!

I just released an alpha version of the plugin that's compatible with Zotero 7 here: https://github.com/tefkah/zotero-night/releases/tag/0.1.0-0

Please check it out and let me know what you think ❤️

**Comment by happyTonakai** [comment]
Everything works fine except that the default PDF filter isn't working as expected, as mentioned in #84 .

**Comment by freshman-x** [comment]
Thank you for your outstanding work

in the dark pdf filter, The yellow highlighted markers are a little light in color（黄色高亮标注的颜色有一点淡了）. Blue, too

zotero7.0.0-beta.36+3ef1f0992

OS (MacOS 13.2）
![](https://user-images.githubusercontent.com/53373482/262009005-755ffead-b917-472d-a751-8c504be8dc04.png)

**Comment by aik2mlj** [comment]
Huge thanks for your awesome work! I notice the pdf filter cannot be toggled on in zotero 7 on a wayland session, GNU/Linux.

**Comment by tefkah** [comment]
@aik2mlj Ah that sucks, are you using the latest version (0.1.0-1)? The initial release was not able to do the pdf filter properly

**Comment by tefkah** [comment]
Or are you saying it's specific to Wayland and is working on X11? I currently do not have a Linux box I can try this on unfortunately

**Comment by aik2mlj** [comment]
@tefkah Hi, I'm using the latest version 0.1.0-1, and I tested on both X11 and wayland, the pdf filter does not work neither.
