### ISSUE TITLE
[BUG] no Dark background in pdf (to fix change the "Default PDF Filter" setting)

### ISSUE THREAD

**Issue by Submarinee** [tefkah/zotero-night#128]
I cannot find the button to switch the background color of the PDF. I downloaded the latest version and the PDF is still showing a white background. I am using a Windows computer. How can I change the background of the PDF to black?

**Comment by Submarinee** [comment]
i can not find the Quick Toggle

**Comment by qdgiang** [comment]
@tefkah I can confirm, I can activate/deactivate the plugin dark mode while in the library UI, but when I'm reading a PDF the button to activate/deactivate is not there.

**Comment by tefkah** [comment]
hmmm strange. are you using the latest version of the addon? Is the Reader UI dark as well, e.g. are the annotations in dark mode?

**Comment by tefkah** [comment]
ah i can actually also reproduce this, weird

**Comment by tefkah** [comment]
ahhh i think I know what causes this.
I changed something about how the default filter is selected, and the previous default setting no longer exists.

If you change the "default pdf filter" setting it should work again!

**Comment by tefkah** [comment]
I will fix this in an upcoming version, for now change the default pdf filter option to any other (you can also change it back if you want) and you should see the filter button again!

**Comment by yitianlian** [comment]
I also meet the same problem just yesterday, any solution?

**Comment by Submarinee** [comment]
I have found the solution.
You may need to restart the zotero and click tool in zotero ,and then click night preference . Then you could select the theme.
![image](https://github.com/tefkah/zotero-night/assets/45026656/e5f2c717-ccf9-4d25-9c0c-7c4ecef7a02d)

![image](https://github.com/tefkah/zotero-night/assets/45026656/eab03294-ba29-46a3-9d46-4c7dde6f98d3)


> I also meet the same problem just yesterday, any solution?

**Comment by Submarinee** [comment]
> I also meet the same problem just yesterday, any solution?

I have found a  solution, you could download the zotero plugin zotero style, it can  change the background.
![image](https://github.com/tefkah/zotero-night/assets/45026656/7ae25003-33f6-4420-b86f-e4e2f36d71a7)
![image](https://github.com/tefkah/zotero-night/assets/45026656/cf523bef-6f71-423c-81e8-4d9288d63b5c)

**Comment by kwmullet** [comment]
I'm running Zotero 6.0.26 on a Mac.  When the tab for a PDF is associated with the main Zotero window, I get a black background, but when I move the tab to a new window (and, incidentally, from an external display to the internal display of an M2 Macbook Air) both the Zotero UI and the PDF background are light again.

**Comment by tefkah** [comment]
@kwmullet do you mean popping it out of the original window? That has not been fixed yet unfortunately

**Comment by tefkah** [comment]
I think this is fixed now.

**Comment by wanemac** [comment]
I cant do it either. My version is 6.0.30. I can see the main panel dark, but not the pdf. Althought I have changed the preferences of zotero-night. 
Thank you

Wanessa

**Comment by mhl66** [comment]
Again: Zotero 6.0.30, plugin 0.4.23, PDFs are NOT DARK. What to do?

**Comment by PepperXZC** [comment]
How about tools -> Night Preferences -> Enable Dark Theme & Matching background? I made it work after reload.
![image](https://github.com/tefkah/zotero-night/assets/103398581/853b11b3-1d31-4b21-a818-bcb5f341cc67)
