### ISSUE TITLE
[BUG] Reader does not get proper styling

### ISSUE THREAD

**Issue by foss-** [tefkah/zotero-night#138]
Thanks so much for this early alpha of Night for Zotero 7 - Zotero just isn't complete without this add-on!

**Is your feature request related to a problem? Please describe.**
In a brief test, PDF files are not shown in dark mode, which was possible in previous versions for Zotero 6. Maybe a known limitation of this early alpha?

**Describe the solution you'd like**
Add option to also show PDF files in dark mode (think colors were inverted?).

**Additional context**
macOS 13.5.1
Zotero 7.0.0b36
Night for Zotero 7 a0.1.0-0

**Comment by tefkah** [comment]
did you press/can you see this button?
<img width="346" alt="image" src="https://github.com/tefkah/zotero-night/assets/21983833/9959c6de-bbd5-4689-9356-edfb76e55ec7">

**Comment by tefkah** [comment]
Also, when you say "PDF Files not shown in dark mode", you mean that the theme of the files is not dark right? not that you cannot see the files at all

**Comment by foss-** [comment]
This is what I am seeing. Seems no dark mode whatsoever is applied to PDF view:
![a](https://github.com/tefkah/zotero-night/assets/5708172/5fa36fd7-d1d0-44b4-9897-ff4582f8c693)

**Comment by tefkah** [comment]
Yes I'm seeing the same thing.

Reason is in between the version of the beta I was using to test and the latest version Zotero redid the PDF reader a bit, hence why my method no longer worked. I've got it running again, expect a fix later today

**Comment by tefkah** [comment]
Should be fixed, let me know if it does not work! 
https://github.com/tefkah/zotero-night/releases#:~:text=Compare-,%F0%9F%8C%8C%20Night%20Zotero%207%20ALPHA%20Release%200.1.0%2D1,-Pre%2Drelease

**Comment by foss-** [comment]
Fix verified ❤️

macOS 13.5.1
Zotero 7.0.0b36
Night for Zotero 7 a0.1.0-1
