### ISSUE TITLE
[BUG] reversed image color using Zotero on mac in dark mode

### ISSUE THREAD

**Issue by jackhu-bme** [tefkah/zotero-night#142]
**Describe the bug**
<img width="1114" alt="image" src="https://github.com/tefkah/zotero-night/assets/75958166/eeb1bd06-5fd8-4c35-94ff-30a68c43351c">
The image shown is in reversed wrong color in dark mode.
The correct color is shown as follows in light mode:
<img width="935" alt="image" src="https://github.com/tefkah/zotero-night/assets/75958166/35a7bfd7-b96c-4dca-8668-b1bfeb9e9d1d">

**To Reproduce**
1. Go to Zotero on mac
2. Click on "tools", "night preferences", choose "dark"
3. restart Zotero and watch a image

**Expected behavior**
change only the background color, keep the image color unchanged.

**Screenshots**
offered in the bug part.

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
macos Silicon only tested, with bug

**Zotero Night version (please check that you are on the latest version)**
the latest version 0.4.23 for Zotero 6.

**Additional context**
This sets great barrier for me when reading papers in pdf, a researcher in computer vision 
as the image color is too essential for visualizing the results.
Sincerely thanks, please help me how to Solve It when available.

**Comment by tefkah** [comment]
I agree that this would be nice, but unfortunately it is probably not possible.

Reason being is that I can only really affect the page in it's entirety, I cannot target specific elements of the page like the text or the images. PDFs are basically implemented as a series of images, which means that the only way to change them here is by applying a big filter which, as you can see, inverts the background _and_ the images _and_ the text.

So I can't help you, sorry! There is limited ability to change only the background color of the page, but I cannot change the text and images separately.

I'm happy to be proven wrong though! If you can point to a pdf reader that has dark mode without affecting the images I'll try  to see what they do!
