### ISSUE TITLE
[FEAT] Support epub reader

### ISSUE THREAD

**Issue by foss-** [tefkah/zotero-night#145]
Zotero 7 recent beta introduced epub reader support which is an amazing milestonre for the Zotero team.

It would be fabulous if zotero-night support epub dark mode.

https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types

**Comment by tefkah** [comment]
oh wow totallyy missed this, thank you for bringing it to my attention!
That's so cool that they support that, I will definitely try to support it!

**Comment by tefkah** [comment]
This has been added to the latest release! You cannot change the background yet tho, it will be like  in the picture
