### ISSUE TITLE
[BUG] Dark mode Toggle goes away when soft closing Zotero 7 and open it again on Mac

### ISSUE THREAD

**Issue by toineenzo** [tefkah/zotero-night#146]
**Describe the bug**
When I open Zotero with the extension installed, I can see the Dark mode toggle button. It works great! But when I click the red dot to close zotero (not completely as on the dock it still has a dot underneath it aka soft close) and then open it again, the Dark mode toggle is not there anymore. In previous Zotero 7 betas this would also disable the dark mode function. When I force close Zotero and open it again, it works again.

**To Reproduce**
1. Open Zotero, you see the Dark mode toggle
2. Click on the red dot > close button, Zotero closes but is still on stand by on the dock
3. Open Zotero by clicking the icon on the dock, you can see the Dark mode toggle is not there anymore

**Expected behavior**
See the toggle even when you close zotero (or do any other things)

**Screenshots**
See the following screengrab: 
https://github.com/tefkah/zotero-night/assets/4921397/41ffb331-8d43-433c-ba8f-fde3d5dfe535

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
macOS 13.5 Silicon with Zotero 7.0.0-beta.38+b79e0b3d7

**Zotero Night version (please check that you are on the latest version)**
[Night for Zotero 7 ALPHA 0.1.0-1](https://github.com/tefkah/zotero-night/releases/tag/0.1.0-1)

**Additional context**
N/a

**Comment by tefkah** [comment]
Hmmm annoying, thanks for letting me know! 

Weird that the toggle does not work, at least the theme gets added correctly
