### ISSUE TITLE
Editing comment in pdf reader has black text on dark background

### ISSUE THREAD

**Issue by 7homR** [tefkah/zotero-night#27]
If I highlight a sentence in the pdf reader and then add a comment to the highlight with the annotation pane closed, the text is black on dark background while editing. Once I click out of editing, it is black on white background and much more legible.

![Untitled](https://user-images.githubusercontent.com/102162197/167710684-83643189-2606-4304-a31b-09330af35fb8.png)

**Comment by ThomasFKJorna** [comment]
hmm yeah that looks like ass, i'll fix it, thanks for letting me know!

**Comment by 7homR** [comment]
Great! I can't help, only point out things. Bad at coding, great at complaining.

**Comment by tefkah** [comment]
This should be fixed as of 4.10
