### ISSUE TITLE
Select Area coloured box doesn't show whilst addon enabled

### ISSUE THREAD

**Issue by Victor239** [tefkah/zotero-night#32]
Whilst the addon is enabled in any theme colour the Select Area feature doesn't show the coloured preview box.

Zotero 6.0.7 Linux Flatpak
Night for Zotero 0.4.8

[See video](https://imgur.com/a/XL66p7b)
![](https://i.imgur.com/iuAQvfN.mp4)

**Comment by tefkah** [comment]
Ahah, that's not good, give me a second

**Comment by tefkah** [comment]
Should be fixed in 4.11!
