### ISSUE TITLE
Highlighting offset from cursor

### ISSUE THREAD

**Issue by 7homR** [tefkah/zotero-night#39]
When I begin highlighting a word, the highlight consistently begins a letter or two to the left and slightly above where my cursor is, so that it frequently highlights the line above where I'm clicking. Happens no matter what pdf I'm reading. When I disable the Night plugin and restart, this doesn't happen. Anything I can do to fix? Thanks!

**Comment by dstillman** [comment]
This bug is [leading people to think](https://forums.zotero.org/discussion/comment/412948/#Comment_412948) there's a general problem with text selection in the Zotero PDF reader, so we'd really appreciate if this could be addressed.

**Comment by dstillman** [comment]
@tefkah: Could you acknowledge that you've seen this and are working on a fix? This bug makes Zotero's built-in PDF reader essentially unusable, so we're going to be forced to block the plugin until this is addressed if it's not fixed soon.

I don't know if this happens on all platforms, but I can reproduce it on macOS, and it's really quite bad.

**Comment by tefkah** [comment]
Expect a fix soon!

**Comment by tefkah** [comment]
This should be fixed in https://github.com/tefkah/zotero-night/releases/tag/v0.4.10 as well!
