### ISSUE TITLE
BUG: Settings for default PDF filter not working.

### ISSUE THREAD

**Issue by FeralFlora** [tefkah/zotero-night#42]
I have the Default PDF filter set to "none", but nevertheless, when I open a PDF, it defaults to the dark filter. In the PDF reader toolbar, the toggle for filters defaults to the "sun" symbol, correctly, but the actual filter applied is the dark filter.

To get the "none" setting, I have to use the toolbar toggle to cycle through the options back to "none"/ the sun symbol, at which point I will finally have no filter applied.

**Comment by tefkah** [comment]
Should be fixed now
