### ISSUE TITLE
Dark mode/filter doesn't work for PDF reader any more (macOS 12.5)

### ISSUE THREAD

**Issue by domiden** [tefkah/zotero-night#53]
First of all, thank you very much for your hard work!

Unfortunately, I have to report a potential bug. Since 4.10 the dark mode/filter for the PDF reader doesn't seem to work any more. Additionally, it appears that the dark mode and filter setting is lost after each app restart or quit.

Option for PDF filter is also missing:
<img width="1642" alt="Screenshot 2022-07-31 at 15 42 40" src="https://user-images.githubusercontent.com/24540355/182029470-b6703514-9e00-4b2a-a2da-a37f58b8dd9d.png">
<img width="212" alt="Screenshot 2022-07-31 at 15 44 50" src="https://user-images.githubusercontent.com/24540355/182029320-52fe5475-bbfd-48f1-a786-0092ae5cb165.png">

- Zotero version: 6.0.10
- OS version: macOS Monterey (12.5)
- Plug-in version: > 4.8

Do you need any further information, please let me know?

Kind regards

**Comment by tefkah** [comment]
Hmmmm, I'm also on MacOS 12.5, works fine here. Could you update to the latest version and/or restart Zotero?

**Comment by domiden** [comment]
@tefkah: Yes, several times. I have also reinstalled the plug-in more than once. I tried different version. From version `4.10`, `Zotero` have trouble to present the dark mode/filter correctly. I just tested it for `Zotero v6.0.11`, the problem continues.

**Comment by tefkah** [comment]
Are you on an intel or M1 mac?

**Comment by tefkah** [comment]
Also, I see I'm actually on the Zotero Beta (https://www.zotero.org/support/beta_builds), maybe you can give that a shot?

**Comment by tefkah** [comment]
And could you list other plugins you are using?

**Comment by tefkah** [comment]
> From version `4.10`, `Zotero` has trouble to present the dark mode/filter correctly

When you say "has trouble", do you mean that this always happens, or only sometimes?

**Comment by domiden** [comment]
> Are you on an intel or M1 mac?

Intel MacBook Pro (2017)

> Also, I see I'm actually on the Zotero Beta (https://www.zotero.org/support/beta_builds), maybe you can give that a shot?

I've just tried it, the problem is persisting.

> And could you list other plugins you are using?

I don't have time currently for testing through. Perhaps at the weekend.

![Screenshot 2022-08-01 at 14 35 25](https://user-images.githubusercontent.com/24540355/182149047-ea27c2ef-8f6b-4cd8-9ccb-4f505fffae3b.png)
![Screenshot 2022-08-01 at 14 35 47](https://user-images.githubusercontent.com/24540355/182149063-a2738355-69db-4b39-93e1-604b03756ac0.png)

> > From version `4.10`, `Zotero` has trouble to present the dark mode/filter correctly
> 
> When you say "has trouble", do you mean that this always happens, or only sometimes?

Happens always, no exception.

**Comment by tefkah** [comment]
It doesn't seem to be any of those, nor PDF Translate. The PDFs are still dark.

btw @windingwind great job on all these plugins!! They're honestly amazing, let me know what I can do to make Zotero Night integrate with them better! Ideally I'd be able to expose some sort of API where other developers are able to add custom CSS to Night or something, I think doing it the other way around (me supporting every little plugin) will not work.

**Comment by tefkah** [comment]
Okay I installed literally every plugin on your list and it STILL works, so I'm out of ideas

**Comment by kinman1** [comment]
First, I will add my thanks to you for working on this plug-in; sorely needed. 
I can report the same problem as @domiden; the pdf reader itself does not show the dark icon, while the annotations pane does. 

I'm on a MacStudio M1 Max; 
OSX 12.5; 
Zotero 6.0.10. 

Extensions are modest:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/3004126/182251413-c085fba6-e1bc-4c60-b092-43acdd587160.png">

Let me know if you need/want any other information.

**Comment by kinman1** [comment]
Upon further review, I got it to work. 

Here was my fumbling around:

After installation, restarted Zotero
Under Tools|Night Preferences, clicked on "Enabled Dark Theme."  A check only appears in the checkbox when clicking twice, but the Dark Theme turned on for Zotero in the background while the Night Preferences drop down menu was still open. 
Clicked on the "Dark" radio button. Closed the Night Preferences menu. 
In the vvveeerrryyy right hand corner of Zotero, an icon appears. 

<img width="52" alt="image" src="https://user-images.githubusercontent.com/3004126/182252864-c3c36f3b-3116-4238-a139-07bcb70fdb4d.png">

Toggling that icon now turns on the dark mode both for Zotero AND in the pdf reader. 

Thus I got the plug in to work as advertised, just with a few more clicks than was obvious. 

Thanks again for creating this.

**Comment by windingwind** [comment]
> It doesn't seem to be any of those, nor PDF Translate. The PDFs are still dark.
> 
> btw @windingwind great job on all these plugins!! They're honestly amazing, let me know what I can do to make Zotero Night integrate with them better! Ideally I'd be able to expose some sort of API where other developers are able to add custom CSS to Night or something, I think doing it the other way around (me supporting every little plugin) will not work.

Wow thanks!

It would be perfect if there could be an API to darken the windows created by other plugins.

I’ve added some naive support to dark mode in the iframe windows, as they seem to be natively darken on Linux dark mode. The only one thing Zotero Night will need to take care is the XUL windows, which simply used Zotero’s style. And that would not be too difficult I think!

I have two ideas:

1. Let the Z Night take control of the style. The Z Night expose a slot for Window objects and let it decide when to darken these windows or not, as the Z Night has some switch to turn on/off the dark mode. Add-ons append their Window objects to the slot;
2. Let other add-ons decide the style. This would be easier to implement. Just make the function a public method and add-ons call the function to style the Window.

I would prefer the former solution, which seems to be more natural for users. When they decide to turn on/off the dark mode, the plugin windows would change style too.

**Comment by domiden** [comment]
> Upon further review, I got it to work.
> 
> Here was my fumbling around:
> 
> After installation, restarted Zotero Under Tools|Night Preferences, clicked on "Enabled Dark Theme." A check only appears in the checkbox when clicking twice, but the Dark Theme turned on for Zotero in the background while the Night Preferences drop down menu was still open. Clicked on the "Dark" radio button. Closed the Night Preferences menu. In the vvveeerrryyy right hand corner of Zotero, an icon appears.
> 
> <img alt="image" width="52" src="https://user-images.githubusercontent.com/3004126/182252864-c3c36f3b-3116-4238-a139-07bcb70fdb4d.png">
> 
> Toggling that icon now turns on the dark mode both for Zotero AND in the pdf reader.
> 
> Thus I got the plug in to work as advertised, just with a few more clicks than was obvious.
> 
> Thanks again for creating this.

This work for me as well! The style also persists after an app restart or quit. Thanks for the hint!

**Comment by tefkah** [comment]
Do you still have this problem in the latest version?

**Comment by domiden** [comment]
@tefkah: No, not at all any more. Thanks!

**Comment by tefkah** [comment]
Great!
