### ISSUE TITLE
[BUG]Dark mode, color offset

### ISSUE THREAD

**Issue by zhl111** [tefkah/zotero-night#65]
![image](https://user-images.githubusercontent.com/29135984/187233268-6a5eb702-682c-4c71-bf15-d8ce7a489d33.png)

**Comment by voidffu** [comment]
me too

**Comment by tefkah** [comment]
could you provide some more info, e.g. what your system is, which version of zotero/night you are using?

works fine for me on macos 13.0 / Night 4.16

**Comment by xiangyi-wang** [comment]
![image](https://user-images.githubusercontent.com/22881957/192128556-11eacd3d-248e-4271-b7d2-323e15f0b154.png)
 Windows 10 21H2  19044.1706

**Comment by tefkah** [comment]
Thank you! Is this the case with all papers?

**Comment by xiangyi-wang** [comment]
> Thank you! Is this the case with all papers?

Yes

**Comment by tefkah** [comment]
this seems to happen on windows, not macos, im still looking into this

**Comment by GritLs** [comment]
Yes, my platform is win11
&nbsp;


Ls
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thomas F. K. ***@***.***&gt;; 
发送时间: 2022年11月28日(星期一) 晚上10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tefkah/zotero-night] [BUG]Dark mode, color offset (Issue #65)





 
@GritLs  are you also on windows?

**Comment by tefkah** [comment]
So I think I've narrowed it down somewhat to Windows' ClearType Rendering. I set up a VM and the color offset is very noticeable, apologies for not getting on this faster!

Here with ClearType turned off
![image](https://user-images.githubusercontent.com/21983833/204484999-1338b42b-7fcc-492a-9756-2a81d8ccbe59.png)

Here with ClearType turned on
![image](https://user-images.githubusercontent.com/21983833/204485249-c2cad167-0cdd-410d-a575-17c58a255571.png)

I'm not sure if there's anything I can do about this. It does seem to depend on the parameters of the filter, e.g. in black mode it's not noticeable at all.

![image](https://user-images.githubusercontent.com/21983833/204485604-1b6189a7-f176-4b80-8ba7-bed5959e275a.png)

**Comment by tefkah** [comment]
I say that, but after a lot of manual fucking with the filter... no bleed WITH cleartype! 
![image](https://user-images.githubusercontent.com/21983833/204493289-b4df8991-c473-43af-8146-c0ab476e6d14.png)

The important part seems to be the `saturation` filter, if that's too high (over 400%) ClearType becomes very visible.

This should be fixed in the next release!

**Comment by tefkah** [comment]
Hmmm looking at it on my Mac again there is still _some_ bleed, but it's at least a lot less!

**Comment by tefkah** [comment]
![image](https://user-images.githubusercontent.com/21983833/204496499-895a2f56-e1c2-4593-862a-9aa9a49e0eb1.png)
Think i managed to make it even less noticeable.
