### ISSUE TITLE
[FEAT] Math support in notes

### ISSUE THREAD

**Issue by mjthoraval** [tefkah/zotero-night#73]
Zotero has recently added in the beta an option to add math equations:
https://forums.zotero.org/discussion/99411/available-for-beta-testing-math-support-in-notes
However, they do not display correctly with this plugin.
Is it possible to support also the math equations?

**Comment by tefkah** [comment]
Could you provide a screenshot?

**Comment by mjthoraval** [comment]
Here it is: [screenshot](https://drive.google.com/open?id=10zIleX8aajxCYxFJdaHg2BZc0KE9W5CH&authuser=mjthoraval%40gmail.com&usp=drive_fs).

**Comment by tefkah** [comment]
Thank you! I'll paste it here for easier reference: 
![image](https://user-images.githubusercontent.com/21983833/191786650-a3bab1b7-463d-4d55-918c-2e47be998e6a.png)

**Comment by tefkah** [comment]
This will take some time as I'm no longer able to debug Zotero on my machine, I will see whether I can do this with the latest dev version of Zotero 7, otherwise this will have to wait unless someone can provide me with some css-selectors for these elements!

https://www.zotero.org/support/dev/zotero_7_for_developers

**Comment by mjthoraval** [comment]
Thank you very much for looking into this.

**Comment by AlexMeier99** [comment]
Hi @mjthoraval,

![Screenshort of rendered math content in Zotero note editor](https://user-images.githubusercontent.com/17048656/195999529-01e13508-9592-4550-9609-a71f4e705b11.png)


To support further investigation by @tefkah I'll attach a screenshot of the DOM tree above. The following css should fix the bug.

```css
[theme="dark"] math-inline,
[theme="dark"] math-display {
   color: white;
}
```

**Comment by tefkah** [comment]
Should be fixed in the latest version!

**Comment by mjthoraval** [comment]
Thank you very much @tefkah & @AlexMeier99, it is working nicely now.
