### ISSUE TITLE
The new Zotero version (6.0.15) offers the ability to split the pdf reader pane vertically or horizontally, but the second pane can't be set to dark mode.

### ISSUE THREAD

**Issue by 7homR** [tefkah/zotero-night#76]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**

**Zotero Night version (please check that you are on the latest version)**

**Additional context**

**Comment by AlexMeier99** [comment]
Hi @7homR

I noticed the same bug. I just opened the dev tools to see how the zotero devs have implemented this.

I'll add a screenshot of the DOM tree for @tefkah for further investigation right below:

![2022-10-05_zotero_split_view](https://user-images.githubusercontent.com/17048656/194051437-bd5e0954-8810-4dc4-befa-38fa9929a371.png)

As highlighted above the main issue is (to my personal understanding) the isolation of the second `pdfViewer`. So for adapting the theme js code for interacting with both [`#viewer`](https://github.com/tefkah/zotero-night/blob/c5f31c96ae508f9063b12111da8233c0c9f23cdf/content/zotero-night.ts#L188) nodes would be required.

**Comment by donkikos** [comment]
Is there a chance we might get this fixed anytime soon? I would really appreciate it.

**Comment by tefkah** [comment]
hi! im so sorry that this isn't working, ive tried to fix this at some point but its proven more difficult than id want. basically i have to know when the pane splits, and i cant really figure out how to do that effectively. If anyone has some idea on how to do this please let me know!

**Comment by tefkah** [comment]
This will be fixed soonish

**Comment by tefkah** [comment]
This should be fixed now
