### ISSUE TITLE
[BUG] Dark filter not working in pdf reader

### ISSUE THREAD

**Issue by margin-bqk** [tefkah/zotero-night#78]
**Describe the bug**
The UI gets dark but pdf won't

**To Reproduce**
1. Install the plugin
2. Restart Zotero
3. Go to tools-night preferences
4. Enable dark theme and choose dark or matching background

**Expected behavior**
Both UI and Pdf get dark

**Screenshots**
![image](https://user-images.githubusercontent.com/67771037/196959304-f4217227-119e-4125-ba87-addb7bf4e0fb.png)
P.S In this picture I went to night preference the second time after pdf reader had fail to go dark. And I discovered that the "Enable dark theme" tickbox still stayed not selected. Should this probably be to do with the problem?

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
Windows

**Zotero Night version (please check that you are on the latest version)**
0.4.16

**Comment by humanplayer2** [comment]
Try [this workaround](https://github.com/tefkah/zotero-night/issues/64#issuecomment-1236097028), it worked for me.

**Comment by margin-bqk** [comment]
> Try [this workaround](https://github.com/tefkah/zotero-night/issues/64#issuecomment-1236097028), it worked for me.

Wow, it works perfectly. Thank you!

**Comment by tefkah** [comment]
Do you still have this problem in the latest version?

**Comment by moore-bryan** [comment]
Yes.

**Comment by nOise-maN** [comment]
I have the same problem.
![Uploading Screenshot 1401-09-02 at 12.53.55.png…]()

**Comment by margin-bqk** [comment]
> Do you still have this problem in the latest version?

I'm using 0.4.20 and the problem is fixed now. Thanks for fixing it!

**Comment by moore-bryan** [comment]
This appears to be working for me, too... Thanks for the hard work!
