### ISSUE TITLE
[BUG]Dark filter not working in some case

### ISSUE THREAD

**Issue by itshardforname** [tefkah/zotero-night#81]
**Describe the bug**
the UI get black,but part of the UI and PDf won't,and i've tried the way that #64 said

**To Reproduce**
1. enable the dark mode
2. open a new pdf that not opened before enable the darkmode

**Expected behavior**
all of the UI get dark

**Screenshots**
![image](https://user-images.githubusercontent.com/51430375/199967159-46f86b6c-1d3c-4265-8a9f-4bd8f3c03014.png)
![image](https://user-images.githubusercontent.com/51430375/199967253-67e6208d-8a11-4a13-ae3c-07322222bfd5.png)

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
Windows 11 22h2 22621.674
**Zotero Night version (please check that you are on the latest version)**
0.4.19
**Additional context**
If I unable the dark mode and enable it again,the UI  of the windows that already opend become normal but the bug tills happen when open a new file

**Comment by itshardforname** [comment]
I reboot my pc,and it becomes normal, looks really weird。and won't happend now

**Comment by tefkah** [comment]
Hmmm, glad i works!
