### ISSUE TITLE
[BUG] default pdf filter does not work

### ISSUE THREAD

**Issue by JareBear124** [tefkah/zotero-night#84]
The default PDF filter is not working correctly. When setting the default value to matching background or default it only ever starts the pdfs without a filter. The filter has to be manually changed every time I open a different pdf. The Zotero dark theme functions correctly, and the pdf filter button does give the correct icon. But the pdf filter itself is not correct by default.

1. Open Tool>Night Preferences
2. Change the 'Default PDF filter' radio button to 'Matching background' or 'Dark'
3. Press OK
4. Open any pdf within Zotero
5. The pdf filter is not correct by default

![image](https://user-images.githubusercontent.com/65210406/203520534-606f5f3f-9d68-4086-bd09-a6899d085084.png)

**Expected behavior**
Setting the default pdf filter should change what the pdf filter is when opening a new file

Windows 10 Build 19044.2251
Zotero Version 6.0.18
Zotero Night version 0.4.19

**Comment by happyTonakai** [comment]
Same on Win11 with Zotero 6.0.18 and Zotero Night 0.4.20

**Comment by Mete0** [comment]
Also experiencing the same as OP

**Comment by EnSee** [comment]
Also have the same issue. Checking it's not a settings prob?
Thanks for your work

**Comment by zhbery** [comment]
Same issue. Hope it can be addressed soon. Thanks for the great plugin.

**Comment by Bobo-alcazar** [comment]
Same on Win10 with Zotero 6.0.19 and Zotero Night 0.4.20.

**Comment by luyur** [comment]
Me too.

**Comment by Social-Mean** [comment]
Same on Win10 22H2 with Zotero 6.0.20 and Zotero-night 0.4.20.

**Comment by happyTonakai** [comment]
I downgraded to night v0.4.8 and this works fine for Zotero 6.0.20.

**Comment by zhbery** [comment]
> I downgraded to night v0.4.8 and this works fine for Zotero 6.0.20.

That works. Thank you guy!

**Comment by Social-Mean** [comment]
> I downgraded to night v0.4.8 and this works fine for Zotero 6.0.20.

Yeah, it works well and thanks. But can someone fix the bug in the newest version of zotero-night?

**Comment by tefkah** [comment]
This should work in the latest version, let me know if not.
