### ISSUE TITLE
[BUG] Dark mode select area 

### ISSUE THREAD

**Issue by yuwen-math** [tefkah/zotero-night#87]
When in dark mode, in the built in pdf viewer, when selecting an area to annotate (during click and drag), the selection box is invisible. After you let go, the box is there. 

Using the annotation mode second from the right: 
![image](https://user-images.githubusercontent.com/3828414/206333240-274a6cbc-4305-4a4e-a731-39297de056d3.png)

I'm running the latest version (0.4.20) of Zotero Night and Zotero version 6.0.18, on Linux Mint 21 Xfce.

**Comment by nhan000** [comment]
This is the only issue that prevents me from using this plugin :(

**Comment by tefkah** [comment]
Ah shit, sorry, that sucks. I will try to fix this.

**Comment by nhan000** [comment]
Confirm fixed for Zotero 6
