### ISSUE TITLE
[BUG] Notes cannot switch to bright mode.

### ISSUE THREAD

**Issue by skymagician** [tefkah/zotero-night#90]
**Describe the bug**
Notes cannot switch to bright mode.

**Screenshots**
![zotero_aInzOkbkmJ](https://user-images.githubusercontent.com/25891462/207636294-6134bfe6-7a58-4807-95ee-9a4040f0a653.png)

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
Win11  and MacOS 13.1

**Comment by Florianismeandonlyme** [comment]
It would switch to bright mode once you open your notes in "**Workspace**"
![image](https://user-images.githubusercontent.com/58820847/216239835-24124481-d3f6-4316-8ef3-cc2db09f45d0.png)

**Comment by lanxique** [comment]
Same issue here (Windows 11). Notes in the sidebar are always white-on-black when Night is installed, regardless of whether it's set to bright or dark mode. They are black-on-white when it is not installed. Conversely, the Edit in a Separate Window editor is always black-on-white, regardless of the settings in Night.

**Comment by tefkah** [comment]
I think this is fixed in the latest version.
