### ISSUE TITLE
From Zotero 6 to Zotero 7

### ISSUE THREAD

**Issue by windingwind** [tefkah/zotero-night#92]
Hi, tefkah,

Some friends and I made something that might be helpful to you:
- [plugin template](https://github.com/windingwind/zotero-plugin-template) with full support to Zotero 6 and 7;
- [plugin toolkit NPM package](https://github.com/windingwind/zotero-plugin-toolkit) with commonly used tools for plugins;
- [Zotero type definition NPM package](https://github.com/windingwind/zotero-types), TypeScript definition for the whole Zotero source code.

They are tested on both Zotero 6 and 7, for seamless development for both platforms.

Hope these tools be helpful to you when migrating from Zotero 6 to Zotero 7 and looking for suggestions!

Best,
windingwind
😄

**Comment by tefkah** [comment]
Oh my god you are amazing! I was dreading the transition, especially due to the extreme trial & error nature of developing for  Zotero, but having a full template AND TypeScript definitions?? You're the best, thank you so much for all your work!!

**Comment by tefkah** [comment]
Thanks to you a Zotero 7 was able to be made, thank you so much!
