### ISSUE TITLE
[FEAT] Hope that the releases can have xpi compression package

### ISSUE THREAD

**Issue by luyur** [tefkah/zotero-night#97]
In firefox, xpi could't be downloaded. So I hope that developers can upload xpi compression package file.

As a firefox user, yhank you very much.

**Comment by tefkah** [comment]
If you are on firefox, you should right-click the download link and use "Save link as"!

**Comment by luyur** [comment]
> If you are on firefox, you should right-click the download link and use "Save link as"!

Oh, sorry, I didn't konw this way to save xpi file untile you told me. Thank you!

**Comment by tefkah** [comment]
glad it worked!
