### ISSUE TITLE
Dark Mode not working even after installing the addon

### ISSUE THREAD

**Issue by abhijithnraj** [tefkah/zotero-night#98]
**Describe the bug**
Dark Mode not working even after installing the addon. Followed the same steps as given in the video on README.

Thanks for developing the addon.

**To Reproduce**
- Went to releases page and downloaded zotero-night-0.4.20.xpi. 
- Opened Addons, Install Addons from File and Added zotero-night-0.4.20.xpi
- Restarted Zotero
- Zotero was still in light mode

**Expected behavior**
Zotero to be opened in Dark Mode

**Screenshots**
Not applicable

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
OS: Manjaro Linux 22.0
Linux Kernel Version: 5.15.85-1-MANJARO

**Zotero Night version (please check that you are on the latest version)**
Zotero Version: 6.0.19-beta.3+89bc09469

**Additional context**
Not Applicable

**Comment by amera6** [comment]
I'm also encountering this same issue but on Windows

**Comment by LennyHirsch** [comment]
Another possible reason is that Zotero Night isn't enabled by default.
Go to Tools > Night Preferences and click "Enable Dark Theme" to fix.

Not sure if this is the case on MacOS/Linux as well, but was the case for me on Windows 10.

**Comment by tefkah** [comment]
I think this is fixed it the latest versions of the plugin, please reopen or let me know if its not!
